### ISSUE TITLE
Prefab -> Hierarchy dragging issue

### ISSUE THREAD

**Issue by VergilUa** [LogicalError/realtime-CSG-for-unity#222]
Whenever I drag prefab from project view to the hierarchy, it automatically parents it under random CSGModel object. This is really inconvienient, since I'm already hovering it on top of the object I want the prefab to be parented to.

v.1.504

**Comment by LogicalError** [comment]
Thanks for reporting this, I'll take a look

**Comment by VergilUa** [comment]
Any progress on this one?

**Comment by LogicalError** [comment]
I just released version 1.509 here: https://realtimecsg.com/updates/
It should fix this issue (and boy did I need to work around some unity issues for this)
Let me know if this works for you

**Comment by LogicalError** [comment]
I will close this ticket once this version is available from the asset store

**Comment by VergilUa** [comment]
Thanks, I'll check it out :)

**Comment by VergilUa** [comment]
Ok, Seems like this is still an issue with 1.509 [Unity 2017.2.0f3], nothing has changed.
Even with RealtimeCSG disabled (ctrl+f3) it sometimes parents dragged in scene model/prefab under the closest picked CSGModel.

**Comment by LogicalError** [comment]
Ok, well there are several things going on here.

First of all, in the original ticket you mentioned dragging and dropping in the hierarchy, not the scene. 
So that's what I fixed. 

Secondly, dragging a csg object into the scene is as currently designed, that is not a bug. 

The reason for this is that the default unity drag & drop operation would drop your csg object to the bottom of the hierarchy, outside the model you're dragging and dropping on. This means that if you drag something that contains a substractive brush, like a window, it would _not_ interact with the wall you drag & drop it on if it's not part of the same model

"Also, this happens even if the dragged item doesn't dropped directly on top of the hierarchy item."
The reasoning for this is that, since brushes should be parts of models, you're more likely to want your brush to be part of the last model you worked on.

I'm open to suggestions, of course ..

**Comment by VergilUa** [comment]
Yeah, scene dragging is seems to be working fine, it's just hierarchy issue now.

It becomes an issue when you're trying to sort hierarchy, or put prefabs, or 3D models under specific root. Those, that do not have any CSG components attached to them.

Like imported to Unity fresh .fbx dragged into scene/hierarchy view auto-parents to the CSGModel. 

Here's how to repro:
   - Open scene that contains any CSGModel;
   - Drag non-csg model/prefab and hover over the hierarchy item, or in the space between hierarchy items;
   - Release it. It parents automatically to the CSGModel, even though prefab/model doesn't have any CSG components on it.

However, I've noticed that now, if I don't drag & drop it on items, but rather to the empty space in the hierarchy, it doesn't parent it.

I'm compeletely fine on how brushes are handled, it's that everything else getting messed.

**Comment by LogicalError** [comment]
Ah ok, so it has nothing to do with drag & dropping brushes, but with drag & dropping Renderers!
Apparently the code that handles drag & dropping meshes on brush surfaces in the scene, also (unintentionally) is active while drag & dropping in the hierarchy and it's this which is causing the weird behaviour there. I'll have a fix in the next version

**Comment by LogicalError** [comment]
FYI: This was fixed in one of the recent version, but forgot to mention it here
let me know if you still have any issues
