### ISSUE TITLE
[Fix Available 1.314] 'Mesh collider needs to be readable' error on play 

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#62]
On play the following error occurs
 “This MeshCollider requires the mesh to be marked as readable in order to be usable with the given transform.”
(reported through email)

**Comment by LogicalError** [comment]
This issue is fixed in version 1.314 which is available on the update site!
( http://prenominal.nl/updates/index.php )

I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket

**Comment by LogicalError** [comment]
This version is now available on the asset store, so closing ticket

**Comment by Alvalol** [comment]
@LogicalError  Request to reopen this one, still occurs on 2019.3.7f1
